### ISSUE TITLE
npm init @hapipal paldo-riddles command is not working

### ISSUE THREAD

**Issue by kentezrabetita** [devinivy/hapipal.com#72]
creating a hapipal project somehow does not work. this worked last week. is there a problem in the package itself?
i'm following this guide from hapipal website: https://hapipal.com/getting-started#installation

i have tried:

- resetting the registry path
- using other node versions
- creating the directory first and then run `npm init @hapipal`

```
❯❯ npm init @hapipal paldo-riddles

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-paldo-riddles - Not found
npm ERR! 404
npm ERR! 404  'create-paldo-riddles@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kingking\AppData\Local\npm-cache\_logs\2022-05-26T07_47_02_149Z-debug-0.log
```

**Comment by devinivy** [comment]
I think the most likely issue is support of scopes (e.g. `@hapipal`) in `npm init`.  Which version of npm are you using?  You can check with `npm -v`.

Just to add to that— the error you've posted indicates npm is trying to install a package named `create-paldo-riddles`, when it should be installing `@hapipal/create`.  The package that it installs is based on the command line arguments passed to `npm init`.  As a gutcheck I just tried this out on npm v7.24 and it worked as intended.

Hope this helps!

**Comment by kentezrabetita** [comment]
tried using the latest version of node and also updated npm. it still produces the same error. 

-  `node -v v18.2.0`
- `npm -v .11.0`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-paldo-riddles - Not found
npm ERR! 404
npm ERR! 404  'create-paldo-riddles@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kingking\AppData\Local\npm-cache\_logs\2022-05-27T13_44_13_183Z-debug-0.log
```

thanks for the reply btw!

**Comment by devinivy** [comment]
Dang!  I looked back, and had a very similar issue a while back: https://github.com/hapipal/examples/issues/19

I am pretty sure this is a windows-specific issue, since that user was able to run it fine using the same installation but using Windows Subsystem for Linux (WSL).  Sadly I don't have access to a Windows machine, so this is tricky for me to troubleshoot on my end, but it's pointing towards an npm bug on Windows.

In the meantime you can run these steps instead to get a fresh installation:
```
git clone --depth=1 --origin=pal --branch=pal git@github.com:hapipal/boilerplate.git paldo-riddles
cd paldo-riddles
git checkout --orphan main # New branch without history
git fetch pal --tags
```

This is essentially all `npm init @hapipal` is doing for you :)

**Comment by kentezrabetita** [comment]
yeah i saw that one earlier. it's probably windows causing the issue. thank you for helping me with this!

**Comment by ashelman-ec** [comment]
I hit this issue too, using Windows 10 with node v12, v14, and v16 (tried all three).

It would be nice to have hapipal run on Windows, but I'm new to Node and don't know enough to debug this and attempt a fix (or to prove the bug is in Node for Windows & report a bug there). :-(

**Comment by ashelman-ec** [comment]
Tried the workaroud above, but I needed to also run this command afterward to install dependencies:
`npm install`

However, that revealed problems below. Does this mean that the boilerplate needs to be updated with correct dependencies?
```
\paldo-riddles> npm install
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/eslint-config-hapi@13.0.2: This module has moved and is now available as part of @hapi/eslint-plugin. Please update your dependencies as this version is no longer maintained and may contain bugs and security issues.
npm WARN deprecated @hapi/eslint-plugin-hapi@4.3.6: This module has moved and is now available at @hapi/eslint-plugin. Please update your dependencies as this version is no longer maintained and may contain bugs and security issues.

added 295 packages, and audited 296 packages in 40s

35 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by Nargonath** [comment]
Yes @ashelman-ec, you guessed it right. The boilerplate needs to be updated. If anyone's willing to make a PR for it, we're open to it.
